server:
  port: 8887

Github:
  Client_id: 1885fcec32c1656b5e00
  Client_secret: e88e7999cebe9defbf3018d9c390d128308d3aa3
  Redirect_uri: http://localhost:8887/callback
TengXun:
  Cos_secretid: AKID3uWnAHGl7G9rMbCNsSpxsZ1D9pIYtIm0
  Cos_secretkey: 81gCxYzA6nEPN7bpnWrwlNnx50g6GAsM
  Cos_region: ap-chengdu
  BucketName: blog-1301453407

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: admin
mybatis:
  type-aliases-package: com.jxnd.yuhaojun.blog.model
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    max-size: 100MB
    max-history: 15
    path: logs/blog.log
  level:
    root: info
    com:
      jxnd:
        yuhaojun:
          blog: debug
