package com.jxnd.yuhaojun.blog.model;

public class Active {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.id
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.titile
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    private String titile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.time
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.img
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.gmt_create
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.gmt_modified
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.end_time
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.statu
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    private Integer statu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.id
     *
     * @return the value of active.id
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.id
     *
     * @param id the value for active.id
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.titile
     *
     * @return the value of active.titile
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public String getTitile() {
        return titile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.titile
     *
     * @param titile the value for active.titile
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public void setTitile(String titile) {
        this.titile = titile == null ? null : titile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.time
     *
     * @return the value of active.time
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.time
     *
     * @param time the value for active.time
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.img
     *
     * @return the value of active.img
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.img
     *
     * @param img the value for active.img
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.gmt_create
     *
     * @return the value of active.gmt_create
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.gmt_create
     *
     * @param gmtCreate the value for active.gmt_create
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.gmt_modified
     *
     * @return the value of active.gmt_modified
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.gmt_modified
     *
     * @param gmtModified the value for active.gmt_modified
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.end_time
     *
     * @return the value of active.end_time
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.end_time
     *
     * @param endTime the value for active.end_time
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.statu
     *
     * @return the value of active.statu
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public Integer getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.statu
     *
     * @param statu the value for active.statu
     *
     * @mbg.generated Wed Mar 11 11:59:59 CST 2020
     */
    public void setStatu(Integer statu) {
        this.statu = statu;
    }
}