package com.jxnd.yuhaojun.blog.model;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.age
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.sex
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.img
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.mailbox
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String mailbox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.qq
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private Long qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.school
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.autograph
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String autograph;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.birthday
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.city
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.constellation
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    private String constellation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.age
     *
     * @return the value of person.age
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.age
     *
     * @param age the value for person.age
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.sex
     *
     * @return the value of person.sex
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.sex
     *
     * @param sex the value for person.sex
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.img
     *
     * @return the value of person.img
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.img
     *
     * @param img the value for person.img
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.mailbox
     *
     * @return the value of person.mailbox
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.mailbox
     *
     * @param mailbox the value for person.mailbox
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.qq
     *
     * @return the value of person.qq
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public Long getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.qq
     *
     * @param qq the value for person.qq
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setQq(Long qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.school
     *
     * @return the value of person.school
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.school
     *
     * @param school the value for person.school
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.autograph
     *
     * @return the value of person.autograph
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getAutograph() {
        return autograph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.autograph
     *
     * @param autograph the value for person.autograph
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setAutograph(String autograph) {
        this.autograph = autograph == null ? null : autograph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.birthday
     *
     * @return the value of person.birthday
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.birthday
     *
     * @param birthday the value for person.birthday
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.city
     *
     * @return the value of person.city
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.city
     *
     * @param city the value for person.city
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.constellation
     *
     * @return the value of person.constellation
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.constellation
     *
     * @param constellation the value for person.constellation
     *
     * @mbg.generated Thu Mar 12 08:56:55 CST 2020
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation == null ? null : constellation.trim();
    }
}