package com.jxnd.yuhaojun.blog.model;

public class Videos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.id
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.aid
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    private Long aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.pageCount
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    private Integer pagecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.gmt_create
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.gmt_modified
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.img
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.id
     *
     * @return the value of videos.id
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.id
     *
     * @param id the value for videos.id
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.aid
     *
     * @return the value of videos.aid
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public Long getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.aid
     *
     * @param aid the value for videos.aid
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.pageCount
     *
     * @return the value of videos.pageCount
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public Integer getPagecount() {
        return pagecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.pageCount
     *
     * @param pagecount the value for videos.pageCount
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public void setPagecount(Integer pagecount) {
        this.pagecount = pagecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.gmt_create
     *
     * @return the value of videos.gmt_create
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.gmt_create
     *
     * @param gmtCreate the value for videos.gmt_create
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.gmt_modified
     *
     * @return the value of videos.gmt_modified
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.gmt_modified
     *
     * @param gmtModified the value for videos.gmt_modified
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.img
     *
     * @return the value of videos.img
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.img
     *
     * @param img the value for videos.img
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}