package com.jxnd.yuhaojun.blog.Mapper;

import com.jxnd.yuhaojun.blog.model.Videos;
import com.jxnd.yuhaojun.blog.model.VideosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    long countByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    int deleteByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    int insert(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    int insertSelective(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    List<Videos> selectByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    Videos selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Videos record, @Param("example") VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    int updateByExample(@Param("record") Videos record, @Param("example") VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    int updateByPrimaryKeySelective(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sun Mar 08 13:39:44 CST 2020
     */
    int updateByPrimaryKey(Videos record);
}